### Site info:
title: Artificial Intelligence
tagline: "Solve intelligence and then use intelligence to solve everything else"
author: Rikith Reddy
email: rikith.legend@gmail.com
description: "Human mind and its cognition have always been facinating elements the blog tries to give an understanding of it" # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "Brain, Cognition, Intelligence, Motivation, Control, AI"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rikithreddy.github.io/" # the base hostname & protocol for your site
locale: en_US

### Personal info and site tools info:

#twitter_username: a
github_username:  rikithreddy
#disqus_shortname: freshman21
favicon:     "/images/favicon.ico"
aboutme: Hi, this is Rikith Reddy. I am a research enthusiast keen in the topics AI and Machine Learning, You can find amazing stuff about human mind in my blog. Please do enjoy it. # these are shown on aboutme-sidebar.
aboutme_photo: "/images/121.jpg" # your photo.
google_analytics_key: UA-57979084-1 # put YOUR key here to enable tracking! (blank to disable)


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English (en), Chinese (cn), Japanese (jp), Polish (pl), Korean (kr),  Russian (ru), Turkish (tr), and Indonesian (id).

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "
      Google_search: "Site Search"
      Home: "Home"
      About: "About"
      Guestbook: "Guestbook"
      Subscribe: "Subscribe"

### your Blogroll info, only name can shown on the page.

Blogroll:
      - name: Rikith
        href: http://rikithreddy.github.io/
        title: Artificial Intelligence
      - name: GitHub 
        href: https://github.com/rikithreddy/
        title: Git repos


### Build settings
markdown: kramdown
#highlighter: pygments
kramdown:
        input: GFM
        syntax_highlighter: rouge
plugins_dir: [jekyll-paginate]
paginate: 5
excerpt_separator: <!-- more -->
gems: [jekyll-paginate]
