# Site settings
title: Rikith's Blog
url: "http://rikithreddy.github.io"
baseurl: ""

description: >
  One or more sentences introducing this blog.

# Your information
email: rikith.legend@gmail.com
author: Rikith Reddy
avatar: "http://rikithreddy.github.io/assets/images/profile.JPG"
profile:  "Solve intelligence and then use intelligence to solve everything else"
#twitter_username: twitter_username
github_username:  rikithreddy
profile_links:
  Email: "mailto:rikith.legend@gmail.com"
  GitHub: "https://github.com/rikithreddy"

# You can add more profile links above, or edit _includes/sidebar.html 


excerpt_separator: <!--more-->

header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    About: /about/
    Category: /category/
#    Resume: /resume/   

permalink: /archivers/:title
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
